export enum CategoriesEnum {
    // Categorías de productos
    ELECTRONICS = 'Electrónica',
    COMPUTERS = 'Computadoras',
    SMARTPHONES = 'Smartphones',
    TV_AUDIO = 'TV y Audio',
    CAMERAS = 'Cámaras y Fotografía',
    GAMING = 'Videojuegos y Consolas',
    HOME_APPLIANCES = 'Electrodomésticos',
    FURNITURE = 'Muebles',
    HOME_DECOR = 'Decoración del Hogar',
    KITCHENWARE = 'Utensilios de Cocina',
    CLOTHING = 'Ropa',
    SHOES = 'Calzado',
    ACCESSORIES = 'Accesorios de Moda',
    BEAUTY = 'Belleza y Cuidado Personal',
    HEALTH = 'Salud y Bienestar',
    SPORTS = 'Deportes y Aire Libre',
    FITNESS = 'Equipamiento Fitness',
    TOYS = 'Juguetes y Juegos',
    BOOKS = 'Libros y Revistas',
    MUSIC = 'Música e Instrumentos',
    PET_SUPPLIES = 'Mascotas y Accesorios',
    AUTOMOTIVE = 'Automóviles y Motocicletas',
    INDUSTRIAL = 'Equipos Industriales',
    OFFICE_SUPPLIES = 'Papelería y Oficina',
    ART_CRAFTS = 'Arte y Manualidades',
    GARDENING = 'Jardinería',
    BABY_PRODUCTS = 'Productos para Bebés',
    JEWELRY = 'Joyería y Relojes',
  
    // Categorías de servicios
    HOME_REPAIR = 'Reparaciones del Hogar',
    CLEANING = 'Limpieza y Mantenimiento',
    ELECTRICAL = 'Servicios Eléctricos',
    PLUMBING = 'Fontanería',
    CAR_MECHANIC = 'Mecánica Automotriz',
    DELIVERY = 'Entrega y Mensajería',
    EVENT_PLANNING = 'Planificación de Eventos',
    CATERING = 'Catering y Banquetes',
    HEALTHCARE = 'Servicios de Salud',
    THERAPY = 'Terapias y Bienestar',
    FITNESS_TRAINING = 'Entrenamiento Personal',
    LEGAL = 'Asesoría Legal',
    ACCOUNTING = 'Contabilidad y Finanzas',
    MARKETING = 'Marketing y Publicidad',
    GRAPHIC_DESIGN = 'Diseño Gráfico',
    SOFTWARE_DEV = 'Desarrollo de Software',
    IT_SUPPORT = 'Soporte Técnico',
    CONSULTING = 'Consultoría Empresarial',
    TRANSLATION = 'Traducción e Interpretación',
    EDUCATION = 'Clases y Tutorías',
    MUSIC_LESSONS = 'Clases de Música',
    PHOTOGRAPHY = 'Fotografía y Video',
    TOURISM = 'Turismo y Experiencias',
    PET_CARE = 'Cuidado de Mascotas',
    REAL_ESTATE = 'Bienes Raíces',
    SECURITY = 'Seguridad y Vigilancia'
  }
  